### ISSUE TITLE
Default number of CPUs

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#104]
In earlier versions of the software, the default number of CPUs was 1. Recently, I have reinstalled the software and now the default number of CPUs used seems to be half of the total. One one machine with 6 cores, 3 would be used. On another with 12, 6 would be used. Is there a way to change the default, or do I have to manually set the number to be 1 during each call?

**Comment by yger** [comment]
You are right, I changed the default behavior, but maybe this is suboptimal. This was because some inexperienced users would not even dare changing the number of CPUs, and thus the code was not launched optimally. So currently, the only option is to explicitly set -c 1 when launching the code. But I think I'll switch back to the former behavior, as this makes more sense for the sake of reproducibility.

**Comment by holmescharles** [comment]
Thanks!
