### ISSUE TITLE
[Feature request] Parameters file should indicate whether filtering completed properly

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#105]
Currently the parameters file tracks whether or not filtering has been done. Actually, that's not entirely true. It track whether filtering has started, but not finished. This is an issue if filtering is interrupted: the parameters file will say filtering has been done even though some of the signal is unfiltered.

I propose that the paremeters file's "filter_done" value be a tertiary value rather than a boolean: "unfiltered", "started", and "finished". That way, you can be know whether filtering completed or interrupted. This would be especially useful for working with batches of analyses, where you may accidentally miss one of the analyses crashing or something.

An even better option would be for "filter_done" to instead be changed to a "filtered_to_sample" integer. As filtering progresses, it can be updated to indicate which sample has been filtered up to. Would this be an issue when using multiple CPUs?

**Comment by yger** [comment]
Good idea. Having an integer will be complicated, because of concurrent write of the nodes in parallel, but the least we could do is, as you are saying, to have a more explicit flag (False, started, True). Then, we will be able to warn the user that a filtering was launched an interrupted, so data are likely to be corrupted. I'll implement that asap

**Comment by yger** [comment]
This has been implemented in the master branch: we now have a particular error message if errors are likely to be corrupted because of partial filtering

**Comment by holmescharles** [comment]
Great! Thanks.
