### ISSUE TITLE
Code getting stuck after filtering and median removal 

### ISSUE THREAD

**Issue by roysuva** [spyking-circus/spyking-circus#113]
Hi Pierre, 

The code is getting stuck after filtering and median removal, when -c is set to a value more than 1 with shared memory flag set to True. 
But with -c set to 1, it completes all the steps without hiccup. This of course takes much longer with bigger data files.   

I have verified that this issue with c > 1 shows up in (1) environment cloned from the spec-file that @jschmiedt posted in https://github.com/spyking-circus/spyking-circus/issues/93 which uses openmpi  1.10.2 , as well as in (2) environments with source installations and (3) environments with pip/conda installations. It seems be an issue with memory sharing but it's not clear to me whether it's related to specific version of mpi or related to the system platform. 

I am using Ubuntu 18.04.2, 64 bit arch Linux , spyking-circus 0.7.6. 
Let me know if you have any thoughts. 

Thanks, 
Suva.

**Comment by yger** [comment]
Turning off shared memory is allowing the code to run with several cores?
My first guess would be to say that mpi4py is not properly intalled/linked
to the current mpi installation, but since you said your tried several
environments. We are also using Ubuntu 18.04.2, 64 bit arch LInux, and I
never spotted such a problem. I'll try to investigate, but could you give
me the full details of your conda environment? Or should I take the one
described in #93?

**Comment by roysuva** [comment]
Shared memory      c =               Result after filtering                             Time to complete 
                                                    & median removal                               filtering and median removal
----------------------------------------------------------------------------------------------------
False                       1                  Not stuck                           	                      ~ 5.5 mins 
False 		 	4	         Sometimes stuck/runs 	                           ~1.5 mins
False 		 	8	         Sometimes stuck/runs                                ~ 1.0 min
False                       12                Stuck always                                               ~ 0.5 min 
False                       16 	         Stuck always		                                     ~ 1.0 mins 

True    		       1	        Not stuck                           	                      ~ 4.5 mins
True                         4                 Sometimes stuck/runs                                 ~ 1.5 mins
True                         8                 Sometimes stuck/runs              	            ~ 1 min  
True                        12                Stuck always                                                ~ 0.5 min 
True                        16                Stuck always                                                ~ 1.0 min  


I test ran the code on a single data set varying the number of cores used and whether the memory is 
shared or not. The results are variable when c is limited to a certain range as you can see from above. What struck me is that failure occurs even when Shared Memory is set to False with c > 1, suggesting it may not be an issue with build of mpi4py not being compatible mpi. The local memory usage is pretty low on the machine. The fact that it runs every time with c=1, confirms that the data is not corrupted either. Wondering if this related to how numpy uses multiple cores !! 

I have attached the spec-file for creating the conda env,  if you want to test it in your system using the binary .dat files I shared before. 

[spec-file-linux64.txt](https://github.com/spyking-circus/spyking-circus/files/2920222/spec-file-linux64.txt)

**Comment by roysuva** [comment]
Hi Pierre, 

I am able to create a new environment with matching build and dependencies for mpi4py. Also the numpy patch you pushed to Github eliminated the " result['data_' str(ielec)] " error. I am now unable to reproduce the errors I encountered before. 

The code ran till "mixture removal", but in the step "pre-computing the overlaps of templates using N CPU..." it exited due to lack of memory. This occurred with c=16 CPUs and c=8 CPUs (total 64Gb RAM). I have memory share flag true. I guess the overlap file is big. I have ~6000 clusters, so the overlap matrix has dimensions 12000x12000xNt-1, which might be too large depending on whether its being stored as double/float. Any thoughts on how to resolve this?

**Comment by yger** [comment]
6000 templates ? How many channels do you have ? If not more than 4000, are
you sure the data are properly read ? Otherwise, I would start to reduce
N_t. A size of 3ms should be more than enough. Then, I would reduce the
radius of the templates. Keep it to 100um. What are the values you are
using? This should increase the sparsity of the matrix, and thus decrease
its size. Internally, overlaps are computed as float32 matrix (but it has a
size (2*nb_templates)**2 * (2*Nt - 1)

**Comment by roysuva** [comment]
512 channels, and radius is set to 250um. I stripped the header info and saved the data as int16. I used pdb in the past to ensure that the voltage values are being imported by numpy correctly. 
I testran spike sorting on a 3min recording, and it ran the full course and saved .basis, .clusters, .templates, .overlap and .result files. It yielded ~1643 templates (attached .log and .params file). I could also plot the templates from hdf5 files in matlab (not gui). I am now rerunning the code with the full data set.  

However, the command "circus-gui-matlab /path_to_dir/rawfile0.dat" shows "No templated found! Check suffix?" The files have been saved with the native suffix. Does this mean that the pcs have to be explicitly exported by something like $ spyking-circus rawfile0.dat -m converting -c num_cpu after ? 

Thanks, 

[rawfile0.log](https://github.com/spyking-circus/spyking-circus/files/2933572/rawfile0.log)
[rawfile0.params.txt](https://github.com/spyking-circus/spyking-circus/files/2933574/rawfile0.params.txt)

**Comment by yger** [comment]
No, to launch the MATLAB GUI there is no need to launch the converting
step. I guess something is wrong in the results. If you relaunched the
code, any chance it corrupted the templates.hdf5 file?

**Comment by roysuva** [comment]
I got the GUI to work. With automatic merging on, I am getting around 3000 clusters on 512 channels from 60 mins data (cc_overlap = 0.75), which is ~ 6 clusters per electrode. It's likely that there are duplicates, which I guess can be reduced by increasing cc_overlap to 1. The templates and clusters look reasonable, which is promising that data is being read correctly, but there are signs of overclustering in some cases.  

There is one issue remaining. I had to reduce the number of cores used by MPI to <=8, as I am getting the following error during template overlap calculation if cores>=12. Could this be due to memory overreach? 
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 27522 RUNNING AT Scriabin
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by yger** [comment]
So to reduce the number of templates, with a more aggressive merging, you need to decrase cc_overlap in the [clustering] section (but I would not go too low, 0.9 at max). Is this the one you are talking about, or you are talking about the one in the [merging] section ? In the merging section, this is just a threshold to select tha pairs that you may decide to merge or not. So this will not reduce memory consumption during the clustering/fitting step, just save you some manual curation at the end.
The error you are facing may indeed be due to memory, since you have a high number of templates. But from the log, I can not say much, because this just means that a MPI task crashed for unknown reason... As said, to reduce memory, I would play on N_t and the radius

**Comment by roysuva** [comment]
Pierre,  Thanks for the explanation. Indeed the code ran earlier with rad = 100um (N_t=3ms), but it limits the search radius to only the nearest electrode. I'll play around with the N_t, and radius parameters, to decide on an optimal value that relieves the memory usage.

Regarding clustering, I was referring to the parameters that tune the number of clusters. It seems that "max_clusters", "sim_same_elec", "cc_merge" and "cc_mixtures" all contribute to the final cluster size. Also, "cc_merge" in [clustering], and "cc_overlap" in [merging] during automatic meta-merging, perform the same function i.e. merging templates based on refractory period violations. is there a reason why this is done twice?

**Comment by yger** [comment]
If the data do make sense, then so be it. But this is a large amount of templates. To make the clustering more "aggressive", you must, in the [clustering] section:
- increase sim_same_elec (overlapping clusters found on the same electrode are more likely to be merged. A too high value will lead to errors, so be careful)
- decrease cc_merge (similar templates found accross electrodes will be merged, same as time-shifted versions of the same template. Again, a too low value will lead to errors, so I would not recomment decreasing it below 0.9)

Then, once this is done, you have your dictionary of template, used in the fitting procedure. The cc_overlap value in the [merging] section is not exactly the same as the previous one. This is because, in the meta merging GUI, you want to compute, for all interesting pairs of cells (with templates similar enough, so with a similarity higher than cc_merge) the cross-correlograms and look for putative merges. If you decrease cc_overlap the merging GUI will just be slower, because more pairs will be considered. But it may not make sense to compute cross-correlograms for templates that are really different. Hope I'm clear.

**Comment by roysuva** [comment]
Thanks Pierre for the explanation. This really helps! 

I'm closing the issue now.
