### ISSUE TITLE
Missing params.py

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#139]
The documentation says that after the converting step, a file named "params.py" should exist (https://spyking-circus.readthedocs.io/en/latest/advanced/gui.html#id6). I believe this files should exist in MYDATA/MYDATA.GUI (if the data being processed is called MYDATA.dat or the like). However, I do not see this file in the aforementioned directory, nor can I find it anywhere else (e.g., with a 'find * -name "params.*"' call).

**Comment by yger** [comment]
Which version of the software are you using? I guess this file is
automatically created during the converting step only since 0.8.1. Before,
it was created only when the circus-gui-python script was launched.

Best

Pierre

Le mer. 24 juil. 2019 à 19:28, Chuck Holmes <notifications@github.com> a
écrit :

**Comment by holmescharles** [comment]
0.8.0.

So it sounds like I should upgrade and try again. I'll report back.

**Comment by holmescharles** [comment]
Upgrading to the most current dev version worked. Thanks!
