### ISSUE TITLE
N_clusters_max parameter in clustering step

### ISSUE THREAD

**Issue by hangletn** [spyking-circus/spyking-circus#147]
Hello, I've been trying to tuning the parameters so that the algorithm is more suited with my dataset. I've been reading the paper associated with the software [https://elifesciences.org/articles/34518](url) (A spike sorting toolbox for up to thousands of electrodes validated with ground truth recordings in vitro and in vivo). In the clustering step in this paper, the parameter N_clusters_max is set as 10, so that for each electrode, there's only maximum 10 clusters. However, when I ran the algorithm with my dataset, some sanity plots from the clustering step shows some electrodes have more than 10 clusters. In this case, there are 13 clusters detected in an electrode.
![cluster_neg_5](https://user-images.githubusercontent.com/52004019/62494043-81b0aa80-b7a0-11e9-8f46-fc78ef9d7c54.jpg)
![waveforms_neg_5](https://user-images.githubusercontent.com/52004019/62495027-d2290780-b7a2-11e9-9b55-d0ea5b187e34.jpg)
I ran the algorithm with all the parameters in the clustering step as default. So I'm not sure whether this is an expected behavior of the algorithms or not. Also, can the user change the parameter N_cluster_max in the params file? I try to look for this parameter but couldn't find it. Thank you very much. I really appreciate your answer!

**Comment by yger** [comment]
I'm travelling, with a limited access to internet, and will only be back
end of the month.

However, in recent versions (>0.8) the parameter max_cluster does not exist
anymore, the code automatically detects how many different clusters can be
done.

**Comment by hangletn** [comment]
Thank you, hope you have a nice trip! When you come back, I hope you can provide more detail about how the algorithm determines the number of clusters.

**Comment by yger** [comment]
Here are more details. So since 0.8.XX, the number of clusters is determined automatically. Basically, the code will try to do as many clusters as possible that do not strongly overlap. Let me explain. Wi the clustering algorithm, we are selecting automatically all points that "deviates" too much from an empirical fit (the red zone in the rho/delta plots). All these outliers point are considered as putative centroids. Then, we create the clusters around these centroids, and for all pairs of clusters with centers x1, x2, we compute a normalized distance between them. If close to 0, clusters are strongly overlapping and they are merged, and if larger, then they are separated. The degree of separation is controlled by the parameter sim_same_elec, leading to what we are calling "local merges". If you want the code to be more aggressive, you increase it, and otherwise you decrease it. I can give you more details if needed.
