### ISSUE TITLE
.MCD Data Files

### ISSUE THREAD

**Issue by Marrekko** [spyking-circus/spyking-circus#174]
Dear Pierre,

after working on my Files with Spyking I found some quite strange results that totally did'nt fit to my original data. Those were generated in a 60 Mea MCS setup. I converted the .MCD Files to binary .raw using the MC_DataTool. When I reviewed the generated .raw files using the simulation mode in MC_Rack I realised that something totally went wrong in the converting Process (e.g. spikes and bursts on dead channels).

Before that I also tried to read the Files using  "MCS_RAW_BINARY" as file format in the data section. This gave me the error message that my .raw files were not generated using MC_Rack. Also, in the Google Discussion Group for this project I saw a comment made by you, saying it is common in your Lab to export .MCD to .raw using MC_Rack.

May I ask you how you did that? I could'nt find any way to do that and the MC_Rack Manual only points to the MC_DataTool when it comes to dataexport. Surely, you can't do anything about the strange output of MC_DataTool, but maybe another converting method would solve my problem.

Thank you so much for any advise and best regards

**Comment by yger** [comment]
In fact, we are also using MC_Datatools to export .MCD into .raw, with or without a header. You must be sure to select, in the software, all the needed channels, and to check if the box unsigned int is ticked or not. Because this will influence the data_dtype format given in the [data] section of Spyking circus. Maybe this is your problem? 
Adding  or not a header is up to you. 
Please check before launching the main algorithm that the data are properly loaded by SC with the preview GUI
>>spyking-circus mydata.dat -p

**Comment by Marrekko** [comment]
Mh, I tried converting in Int16 and UInt16 and changed the configuration file accordingly. I always checked in the preview mode, and at a first glance the Data looks fine. But looking more into Details it came clear to me that the output does not represent my data, which was confirmed by replay them in the simulation mode of MC_Rack. Did you never faced such problems? I really think there is something wrong with the converting by MCDatatools. Im using V.2.6.15. However, did I understand that right that the "MCS_Raw_Binary" is actually a dead function or do you still work with that?

Thank you for your answer, Pierre!

**Comment by yger** [comment]
And are you sure the number of channel is correct in the .prb file? This
could explain a problem while loading the data. mcs_raw_binary is not
deprecated, it can be used if you check the option to export a header in
datatools. This option will add few info in a header, before the raw data,
such as the sampling rate, and the gain factor and spyking-circus circus
will parse the header to recover them. Otherwise, send me a small data file
if possible?

**Comment by Marrekko** [comment]
Dear Pierre,
thank you for the information with the header! Data import and running the code with mcs_raw_binary works fine and correct now!
