### ISSUE TITLE
Filter traces not picking up large spikes

### ISSUE THREAD

**Issue by tStella111** [spyking-circus/spyking-circus#175]
Hello,

We've been trying Spyking Circus for a few days and we noticed that the filter traces are having trouble picking up large spikes. We tried changing some of the parameters (amp_limits, nclus_min, etc) but none of them seems to work well. One thing we noticed was that increasing radius picks up larger spikes but decreases accuracy overall. I was wondering if there's any parameters that I can change to solve this problem. Thank you very much.
![Screenshot (3)](https://user-images.githubusercontent.com/55812987/68317730-9fd0c400-0089-11ea-8444-e28c9da5408f.png)
![Screenshot (5)](https://user-images.githubusercontent.com/55812987/68318334-9e53cb80-008a-11ea-8b52-f60844b37e5c.png)

**Comment by yger** [comment]
Your observations are based on qualitative or quantitative results? What kind of data are you recording: in vivo, in vitro? The algorithms should not really be handling larger spike in a different manner. There will always be few misses, maybe they are more striking visually in case of larger spikes? If the data are not too large, maybe you can share them such that I can have a look

**Comment by tStella111** [comment]
Hi Yger,
Thank you for your fast reply.  So far, qualitative using the preview GUI, we weren't expecting so many large cells to get missed. Our data are in vivo from 32-channel probes, channels spaced by 100 um vertically and 200-um horizontally. Yes, both large and small spikes are being missed.  The data are pretty large, we've been troubleshooting with a truncated block that is still 62MB. Is there a way to share on google drive or dropbox?  Otherwise, let me know if there is a minimum time requirement and I'll truncate it further to email

**Comment by yger** [comment]
So your observations are made on a 62Mb dataset? How long is the global recording? Because the longer, the more accurate the templates, and thus the less you should have misses. From what I understood with your probes, basically channels are quasi independent. So for troubleshooting I would rather just work on a single channel, with a longer recording time. Google drive is fine for sharing (add also the .prb and the .params). The first thing also to do would be to check is the clustering is correct. To do so, activate the option make_plots in the [clustering] section, for example by setting png as a value, and look at the clustering plots.

**Comment by tStella111** [comment]
Yes, we've run it on various amounts of the data but observe the same thing so have cut time to make autosorting faster.  A full data file with all 32 ch is 6.5gb, recording time is ~70 min. I've put a full file for a single channel in the drive folder as well as the truncated file with all 32 channels.  Also the params and prb file.  Should I share with this email?: pierre.yger@inserm.fr

**Comment by tStella111** [comment]
I shared the drive and noticed the filename corresponds to the truncated file with all 32 ch. Let me know if you would like any other combination of data. Also, we do observe some very minor interactions between channels, but never quality spikes on more than one.

**Comment by yger** [comment]
Ok, first, by having a look to your param file, what is the rationale to set N_t to 1ms? This is too short to properly capture the shapes of the spikes, especially the big ones. So I would revert this parameter to its default value, i.e. 3ms. Code should already work much better. Why did you changed it?

**Comment by tStella111** [comment]
> Ok, first, by having a look to your param file, what is the rationale to set N_t to 1ms? This is too short to properly capture the shapes of the spikes, especially the big ones. So I would revert this parameter to its default value, i.e. 3ms. Code should already work much better. Why did you changed it?

We tried snippet durations ranging from 1 to 3 to see how it impacted template fits. I think it was at 1 from a previous attempt, but yes, that is too short. For our data, the fits for detected spikes seem to be best when N_t = 2; the quality of auto-clusters falls off noticeably at N_t = 3. 
Nonetheless, many large spikes get missed in all instances. It does appear to be slightly less of a problem as N_t gets larger, but not by much.

**Comment by yger** [comment]
Can you update to latest version (0.8.5) such that we are sure to be on the same page? By setting merging_param = 0 to avoid any local merge, and have as much clusters as possible, the results looks fine to me, at a first glance. I'll have a more careful look, since your templates are defined on single channels
