### ISSUE TITLE
Sanity Plots

### ISSUE THREAD

**Issue by jstevanovich** [spyking-circus/spyking-circus#243]
Hello, I have a problem with getting views of the waveforms in the sanity plots folder, but not really sure why are they missing. In previous versions of Spyking Circus they were created, but not anymore. Only Cluster, Local merges and Rejecton plots are created.

**Comment by yger** [comment]
Indeed, I can also see that they have been removed, and that the
appropriate code has been commented out. I guess you can bring them back by
removing manually the comments in front of line 1451 - 1469 in
clustering.py. But I'll do it myself asap in the master branch, so that
these plots will be back in 0.9.7.
The reason they have been removed is that since these plots are showing
waveforms in the PCA space, and we thought that it was not so relevant.

Best

Pierre



Le jeu. 16 avr. 2020 à 12:48, jstevanovich <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Actually, just had a look at the code, and in fact this view is not really possible anymore, given that amplitudes are estimated optimally after. Since it was not really crucial, I am not sure this is worth bringing it back into the pipeline. Do you really need it?
