### ISSUE TITLE
problem when adjusting amplitude limits with dispersion

### ISSUE THREAD

**Issue by alihaydaroglu** [spyking-circus/spyking-circus#269]
Hello,

I'm using version 0.9.7, and I'm trying to tighten the amplitude limits for the fitting phase since I have a lot of low-amplitude non-spike snippets in my data being wrongly fitted as spikes. From the documentation, I thought that I could use the dispersion parameter to adjust the amplitude limits used for fitting based on the variation within each cluster, however changing the dispersion parameter led to almost identical results (number of clusters and spikes at the end of multiple runs with different dispersion parameters are within ~5%). 

I looked through the code and found that dispersion is only used in one place in the code, line 1422 of `clustering.py`. This happens inside an if-else block, so if the variable `fine_amplitude` is true, the automatic amplitude calculation based on dispersion is not used at all. Instead, it seems that the `refine_amplitudes` function is used , however, I don't think the method used here to select amplitude limits is documented, or at least I wasn't able to find it. How are amplitude limits refined?

As far as I can understand, the only way for me to manually increase the amp_min limit is to set `fine_amplitude` to False, and then change the dispersion - is this correct? If so, it would be useful to document it so users know that changing dispersion has no effect as long as `fine_amplitude` is True. Is there an alternate way to produce a tighter set of amplitude limits even when `fine_amplitude` is True?

Thanks for your help and the great software!

**Comment by yger** [comment]
You are right. Before 0.9.3, amplitudes were determined with the dispersion parameter, as mean +/- a multiple of the SD in a given centroid (as defined in the paper). However, we introduced the new function refine_amplitudes, as you noticed, that helps to set the amplitudes "optimally", i.e. in order to optimize the MCC (https://en.wikipedia.org/wiki/Matthews_correlation_coefficient) for all the templates. If you want to revert to the old behavior, then indeed you need to set fine_amplitude to False in the  [clustering] section. I'll update the docs accordingly, thanks for spotting that. But in theory, as said, the new method should give better results, and also give you a "purity" score, for every cluster, telling you how confident you can be that this cluster is catching all its spikes (and all its spikes). I'm surprised by the fact that you are telling me templates are fitted while there is nothing. How many channels do you have? Are they independent?

**Comment by alihaydaroglu** [comment]
Thanks for the explanation, that makes a lot of sense. Reverting to the old behavior and changing the lower limit of the dispersion did indeed improve my results. To give you a better idea, the problem I encountered before is seen in the images below (blue traces), where you can see templates being fitted to regions which (to me) look like just noise. It looks like these templates tend to "collect" these noise snippets, and they end up with a very heterogenous set of "spikes" as you can see in the waveform view. These are a result using the new MCC amplitude optimization.

![nospike2](https://user-images.githubusercontent.com/15041006/84964060-1c745800-b0d9-11ea-9484-6bd0d1c5459f.PNG)
![nospike](https://user-images.githubusercontent.com/15041006/84964070-1ed6b200-b0d9-11ea-92c9-d836d274a9f7.PNG)

The data is the same as the one @SaraMati described in #266, it's from an MEA with independent channels.

Thanks!

**Comment by yger** [comment]
Ok, then this is something that I'll study more in depth, because this problem might be "single/independent channel" specific, and did not arise in the benchmarks we made so far. I'll let you know as soon as this is solved, thanks for reporting

**Comment by yger** [comment]
I just realized that indeed, the behavior when templates are defined on few channels can be problematic. Could you simply try adding templates_normalization = False in the [clustering] section, and when launching clustering/fitting, let me know if this is better?

**Comment by SaraMati** [comment]
to give another example, these three segments of the trace have been assigned to one cluster by spyking-circus (in the log, number of global merges = 0 and number of local merges = 50 with bhatta and merging_param 1.5; so it is not the case of automerged clusters) 

The run of spyking-circus was with template_normalization = False and dispersion =(1,5). 

![image](https://user-images.githubusercontent.com/12663563/85926755-8fb36200-b86f-11ea-8477-349dbe854ea6.png)

**Comment by yger** [comment]
As said, the parameter dispersion is not used anymore, at least as long as you don't specify fine_amplitude = False in [clustering]. This is because now, amplitudes are computed "optimally" taken into account all the dictionary. I am not sure to understand what you are showing me here: you have three templates (blue/red/yellow) that looks like very much alike (TemplateView), and you want to pinpoint the fact that they have been used to fit 3 consecutive patterns that do not really match them (TraceView)? If this is the case, I agree, but I can also understand the software: the individual waveforms (WaveformView) looks "similar" to the templates, and the sum indeed should nicely reconstruct the signal. 

However, regarding the optimization: you said in your previous message that you used template_normalization = False, are you sure you do not have a typo? You should use templates_normalization = False (there is an s at templates). 

Let me explain why, and how we now compute "optimally" the amplitudes. When we have obtained the dictionary of templates, we ask the question "what are the optimal a_min and a_max, for every template, that will maximize the MCC (see below), given the full dictionary"? By doing so, we consider snippets from all templates, and from the noise, and we optimize the amplitudes considering the amplitudes of these snippets with all the templates. However, amplitudes quantify "how similar a given template is" to the raw data, and by default, in SpyKING CIRCUS, we used normalized templates to compute them. Why? Because we assumed that what matters most for a template is its shape, not its scaling factor, and it does make sense when templates are defined over numerous channels. However, when this is not the case, and when templates are defined on few channels, using normalized templates can be misleading because we are loosing the information on the amplitudes, while we should not. Indeed, quite often with few channels, templates more or less have all the same shape, up to a scaling factor, that help to distinguish them. This is why, since a while, we recommended to users to set cc_merge to 1 when small channels counts were used. This was not propagated in the new framework to optimize the amplitudes... It should be now in the custom_spikes branch, that I'll merge soon with master. So let me know if, by setting such a parameter, you see a change in your case, or I'll try again with your data as soon as I'll time

**Comment by SaraMati** [comment]
sorry, my bad, I meant "fine_amplite" parameter is set to False. and what I try to show here is that the "similarity" of the three waveforms with the template is really low. so the parameter that defines when to accept a waveform is similar to a template is loose. and I think the problem will be solved with setting a stricter threshold for similarity (i.e. whether a snippet of the trace belongs to a cluster or template). 

I don't think normalization of the waveform is a problem, as far as I've seen in my data, when an electrode is picking up a few neurons in different distances (which causes one amplitude to be drastically smaller than the other, and hence visible by naked eye that there should be two neurons firing, for example) the difference is not limited to the waveform amplitudes. Usually, the template shapes are also different. 

but for now, Spyking-circus is fitting too many snippets of the trace to any template that don't seem similar to it. some are even flat. so even if the template is normalized, those almost flat segments shouldn't be fitted to them. no? 
I am running the algorithm on a dataset with templates_normalization=False and let you know.

**Comment by yger** [comment]
We made some improvements on the amplitudes estimation in latest release (1.0.1). Hope this helps

**Comment by yger** [comment]
If you were using windows, please upgrade the software, since we found a nasty silent bug in the automatic estimation of the amplitudes affecting only windows user, that might explain sub-optimal results (int32 instead of int64 in linux)... This is patched in version > 1.0.6.. Sorry about that
