### ISSUE TITLE
templates occasionally get assigned to the wrong channel

### ISSUE THREAD

**Issue by alihaydaroglu** [spyking-circus/spyking-circus#270]
Hey again,

This is more of a minor issue, but occasionally I get some templates which are assigned to a channel which clearly does not have the highest amplitude. For example, the template seen in the image below (waveform view from phy) is assigned to channel 3, not 31 (on the "clusterview" list in phy). 
![image](https://user-images.githubusercontent.com/15041006/84622290-a7234000-aeaa-11ea-939e-769712eb1791.png)

If I look at the template view of the same template, the part of the template on channel 3 looks like this:
![image](https://user-images.githubusercontent.com/15041006/84622390-dfc31980-aeaa-11ea-952a-576c53e5a8c1.png)
and the part on channel 31 looks like this:
![image](https://user-images.githubusercontent.com/15041006/84622412-ed789f00-aeaa-11ea-99cf-ec65f9b46e09.png)

Is this a bug? The overwhelming majority of templates are assigned to the correct channels, so it looks like something goes wrong in these cases. 

Thanks again!

**Comment by yger** [comment]
Looks like this is a bug in phy, since phy is automatically "computing" this best channel, as the one where the max is obtained. If you see a mistmatch, it means that somehow, indices are mixed up. I'll have a look, try to reproduce the problem and/or open a ticket for them. Meanwhile, maybe exporting with the option sparse_export set to False in the [converting] section can resolve the issue. If you could send me your .params/.prb/.hdf5 in the results folder, it will help (I don't need the raw data and the .GUI export)

**Comment by alihaydaroglu** [comment]
Hi @yger, thanks for the response. The sparse_export=False did not fix it. Where would you like me to send the files, also do you need all the hdf5s in the results?

**Comment by yger** [comment]
If you could send me the .HDF5, the .prb and the .params, I should be able to convert the results and reproduce the error. Because so far, I tried with other dataset, and did not manage to see the problem
