### ISSUE TITLE
recommendations for single channel recordings

### ISSUE THREAD

**Issue by ferchaure** [spyking-circus/spyking-circus#271]
Hi,  I know that is not the focus of spyking-circus, but I'm testing an idea and I have to start using just one channel.
I used a simulated recording with high amplitude spikes (all above 5*MAD) but I got a lot of small amplitude spikes (multiunit and noise with amplitudes below the threshold). I don't understand why that spikes are detected. I will appreciate any help or tip. 

I changed this parameters:

```
spike_thresh = 5
amp_limits = (1, 5) # increase the 0.3 helped a lot
amp_auto = False
collect_all = Falsespikes
ratio_thresh = 1
filter = False
spatial = False
```

**Comment by yger** [comment]
In recent version (>0.9.2), amp_limits is not used anymore, since
amplitudes are set optimally to maximize the Matthew correlation
coefficient for all templates. Can you look at pictures of the
reconstruction (-r argument) to see what these spikes are? Or share the
data with me since that I can double check the behaviour with single
channel recordings?

**Comment by ferchaure** [comment]
> amp_limits is not used anymore
I didn't know that, even when amp_auto = False?  Then is not possible to force spyking-circus to reject all the activity under a threshold?  

I uploaded the data [here ](https://drive.google.com/drive/folders/11CraEwx4mbbCQf39Wa36HjVn7P7Z5qoC?usp=sharing) in mda format (the ground truth is outside the folder) 
I forgot to mention, the peaks are positive (I changed that parameter as well). Maybe, the recording is too fake?

>  Can you look at pictures of the reconstruction (-r argument) to see what these spikes are?

Sorry I run it using spikeinterface, and I just save the results. But at least from the waveforms that I can get using spikeinterface they look like some low amplitude multi-unit and aligned noise.

**Comment by yger** [comment]
Thanks, I'm having a look right now. Just to know, you set the detection only for positive peaks, or both? Meanwhile, to revert the old behavior and I guess get rid of these small noise snippets, you can set fine_ampltiude = False in the [clustering] section (and it should bring back old behavior of selecting the amp_limits)

**Comment by yger** [comment]
Actually, I just realized that I think that when templates are defined on few channels, it could be better to simply add templates_normalization = False in the [clustering] section, keeping the new way of optimizing the amplitudes. I'll make some more tests, but setting this param with your data is enhancing the results already

**Comment by ferchaure** [comment]
> you set the detection only for positive peaks, or both?

Just positive.

> templates_normalization = False in the [clustering]

Cool, I will use that configuration

Thank you, Pierre, for taking the time to help me

**Comment by yger** [comment]
No problem. Let me know if you see the improvements, and as soon as I'll be fully convinced with other benchmarks, I'll make this behavior as a default when templates are only defined on few channels.This is already patched in the branch custom_spikes, that will be merged in master soon

**Comment by ferchaure** [comment]
Hi Pierre, I improved a little my awful single-channel simulations but I keep having too many spurious detections.
Is there a way to totally disable the detection of spikes with an amplitude lesser than a threshold? (I know that is not a realistic scenario).

**Comment by yger** [comment]
Actually, you can easily clean them with the [merging] parameters. If you
set noise_limit to 1, all templates with an amplitude below the detection
threshold will be removed. The more you increase this value, the more
you'll keep only large templates in the merged results (because all
templates with normalized peak, wrr the detection threshold below this
threshold are thrown away). Does that answer your question, or you want to
know how to get rid of small templates even before the fitting procedure is
launched?

**Comment by ferchaure** [comment]
Thanks for the quick response

> you want to know how to get rid of small templates even before the fitting procedure is launched?

If that is just a parameter I would like to try it as well

**Comment by yger** [comment]
We made some optimizations in latest release (1.0.1). Hope this helps, but it should help with low thresholds and amplitudes estimations

**Comment by yger** [comment]
Not sure you were using windows, but if it was the case, I recently found a nasty silent bug there (due to int type of 32bits while it was 64 in linux) that could explain weirds behaviors, such as templates highly contaminated by noise. This has been fixed in the master branch, and only make sense for windows users... If it is, then please upgrade and get back to default params

**Comment by ferchaure** [comment]
thank you for letting me know.
