### ISSUE TITLE
Getting individual results from streams after manual sorting using Phy

### ISSUE THREAD

**Issue by AABBASI89** [spyking-circus/spyking-circus#274]
Hey,
I am performing spike sorting on four .dat files using the stream-mode. After sorting I visualize the output in Phy GUI and perform some manual adjustments. Now I want to split my timestamps into four different files. I saw that there is a way to split the results.hdf5 file into one result file per dat file. So my question is does spyking circus also performs the similar split but for .npy files returned by Phy GUI?

**Comment by yger** [comment]
No, but this is a good point... The circus_multi command is only working with the MATLAB results. Maybe you can try to deconvert (using the deconverting step) the results from phy to matlab, and then use such a command. Not sure this will work, but can be tested

**Comment by GulatiLab** [comment]
So I tested what you suggested. When I "deconvert" my phy results using the deconverting step, it's giving me a new file called result-deconverted.hdf5. However when I am running circus-multi command it is just splitting the result.hdf5 file into result_0.hdf5, result_1.hdf5  etc. So basically my manually sorted timestamps are in the results-deconverted.hdf5 file. I can manually split these files in MATLAB, but I just want to clarify the organization of timestamps. So let's say my first file was recorded for 1hour and my second file was recorded for 30min. So the concatenation of the timestamps will follow an ascending order from 0s-5400s, right? So basically, I can just consider timestamps from 0s-3600s as the timestamps of my first file and anything greater than that as the timestamps of my second file. Kindly clarify?

**Comment by yger** [comment]
You must have use the command, to be sure that you are splitting your deconverting results and not the original ones (not processed via phy)
>> circus-multi youradata.dat -e deconverted

Once this is done, what you have in the first results_0.hdf5 are the spikes during the first hour, and then in the second file the spikes during the remaining 30min.
But, alternatively, you can consider all spikes in your single large result file that have time steps > 3600s to belong to the second file. What the circus-multi script is doing is simply to split the results into sub_files, in order to ease the analysis.

**Comment by GulatiLab** [comment]
Great thanks for your reply. This is working now.
