### ISSUE TITLE
Channel spacing oddity for clustering

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#285]
I am sorting data from a 32 channel linear probe with 50 um spacing between each consecutive channel. I have set my "radius" in the probe file to 90 um. Yet, I am getting some clusters where one or more channels seem much further than 90 um from the other channels. For example, here are two clusters that have activity on the first and the 32nd channel as well as 3 channel in the middle of the probe.

![image](https://user-images.githubusercontent.com/1988783/92620679-86d80700-f288-11ea-9656-a831f7818925.png)

The distance from the first to the second channel in the cluster is 750 um. Is this a bug or am I misunderstanding how the spatial information is used?

Thanks!

**Comment by yger** [comment]
This is not a bug, and this is normal. In recent versions, the radius is used only to constrain the local information used during the clustering. But when it comes to the estimation of the templates, they are estimated as the median of the snippets all over the channels, and only non-zero channels are kept. This is because we wanted to have an arbitrary spatial support for the template, in order to be able to capture long distance interactions (for example axon propagation). So in your case, SC kept the far away channel because the median over the snippets is not zero, and there some information. Hope this is clear

**Comment by holmescharles** [comment]
Ah ok.
I am not sure I would expect axon propagation to be playing a role here.
Should I more often think of these kinds of clusters as "clearly noise/artifact" or not?

**Comment by yger** [comment]
In your case, I don't know what it means. The auto correlogram look nice ? If so I would keep these templates as cells with possible contamination from far away channels. If you look at multiple snippets, you should see this residual activity, so don't know if this is an artefact or not
