### ISSUE TITLE
error running mixture branch

### ISSUE THREAD

**Issue by SaraMati** [spyking-circus/spyking-circus#324]
Hi Pierre, 
I've installed the mixture branch 
pip install --upgrade https://github.com/spyking-circus/spyking-circus/archive/mixtures.zip

and I get this error 

![image](https://user-images.githubusercontent.com/12663563/100672146-8010db80-332f-11eb-8fe5-1959a8fd2e62.png)

the software was running properly on the same data before

**Comment by yger** [comment]
sorry for that. Can you try to upgrade again? In fact, we switch to a new system, and it seems that the label is changing depending on how the software is installed... I usually use git directly, sorry for that

**Comment by SaraMati** [comment]
thanks, the error is lifted. 
but strangely, the results are worse than before (sorting with the master branch). all the parameters were kept the same. 
I noticed that the number of spikes fitted was ~200,000 before which increased to ~2,000,000.

**Comment by yger** [comment]
This branch is in progress, bit still, such a big increase is puzzling. Why did you switch to mixtures and not stayed on master?

**Comment by yger** [comment]
And in this branch, template_normalization should be false

**Comment by SaraMati** [comment]
I also have fitted spikes like the first figure shared in issue #323, as I've reported before, and wanted to follow your advice on using the mixture branch. ok. I will run it with template_normalization = False

**Comment by yger** [comment]
Ok, let me know since I'm always looking for feedback. In this branch, the automated amplitudes are much more robust (so the goal is to have set set automatically fine_amplitudes = True), and we should not have any more problem of normalization during the template matching (it has to be True by default). This should reduce the problem of small spikes that you might have been seen sometimes

**Comment by SaraMati** [comment]
![image](https://user-images.githubusercontent.com/12663563/101064832-6a372c80-3562-11eb-886b-11a5fae9a4f8.png)

**Comment by yger** [comment]
As I already said, you should set template_normalization to False. Note also that we just spotted a silent bug only in windows, hope to patch it tonight. But this branch will be given much better results for your mixtures

**Comment by SaraMati** [comment]
it was False, is remove median mandatory as well? 
![image](https://user-images.githubusercontent.com/12663563/101068256-7ae9a180-3566-11eb-9727-5e6fed528639.png)

**Comment by SaraMati** [comment]
do I have a typo? should it be template_normalization or templates_normalization?

**Comment by SaraMati** [comment]
before it was templates_normalization

**Comment by yger** [comment]
Sorry..... I meant it has to be TRUE. My bad

**Comment by yger** [comment]
If you are using windows, there is still a silent bug in the amplitudes, so give me few hours

**Comment by SaraMati** [comment]
yes, I'm looking at the results and it seems so. ok. sure. I wait. thank you

**Comment by yger** [comment]
done! in fact, this nasty bug should be there since the beginning silently only affecting windows and the auto amplitudes, maybe explaining why you observed bad results.... please let me know how it looks now, with templates normalization set to True (default, and that should not be changed anymore), and fine_amplitudes set to True also. Now, everything should work as expected, hopefully

**Comment by SaraMati** [comment]
glad to hear. Thanks. if it seems good this time, I redo all my datasets. 
I'm commenting out the normalization and fine amplitude. 
![image](https://user-images.githubusercontent.com/12663563/101082719-e5580d00-3579-11eb-8a69-0cb41e334af3.png)

**Comment by yger** [comment]
The branch has been merged to master
