### ISSUE TITLE
(0+unknown) version and request for data re-export 

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#325]
Dear Pierre,

One more question: I just updated SC from the mixture to the last-most release, and upon starting up sorting procedure SC shows version (0+unknown) but sorting goes smoothly. When these data are fed to Phy, an error is shown: 

You should re-export the data because of a fix in 0.6
Continue anyway (results may not be fully correct)? [y/n]

If I agree to re-export, Phy just starts up without any apparent problems. There was no such behaviour with either SC  1.0.1 or mixture releases.
How shall I handle this and are my results fully correct?

System:
Debian 10.6
SC (0+unknown) version
Phy 2.0

Sincerely,
Stan

**Comment by yger** [comment]
Arg, this conversion prompt is a bug, due to a bad handling of your weird
version number displayed when installed via pip/zip... Either you upgrade
(I've fixed that), either you install the software via conda

>

**Comment by sv-bio** [comment]
I removed the version installed via pip and installed the latest version via conda. Now version number is correct (1.0.6) and no errors are shown.
Thanks.

**Comment by mstimberg** [comment]
Just to comment on the (very annoying...) `0+unknown` issue: unfortunately github does not use the `git archive` command to create the zip files, this is why it gets rid of the version information. Instead of using `pip` with the zip file, you can use `pip` with `git+https`, instead. This should work fine and keep the version information (it's somewhat slower though and I'm not 100% sure it works on systems without a git installation). You can put the name of a branch or commit after the `@`, e.g. to install from the `omp` branch use:
```
pip install git+https://github.com/spyking-circus/spyking-circus.git@omp
```
