### ISSUE TITLE
Issue with template matching

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#329]
Dear Pierre,

Could you help me to resolve an issue with template matching (I briefly mentioned it in issue #323): sometimes templates do not visually match real spikes.
Example 1 (from issue #323, but now the focus is on (apparent?) mismatch between the shapes of a spike and template  (in red)):
![image](https://user-images.githubusercontent.com/58944642/101708782-a7397c80-3a96-11eb-97fa-fa4a181326af.png)
and templates:
![image](https://user-images.githubusercontent.com/58944642/101708811-b4ef0200-3a96-11eb-9593-c7d23a784b9e.png)

Example 2:
template (sanity plot also shows only one template.):
![image](https://user-images.githubusercontent.com/58944642/101709091-7d348a00-3a97-11eb-86d6-57b67cbc4b53.png)

spikes, it fitted (some of them indeed look similar to template whereas may others are visually different):
(sample 1)
![image](https://user-images.githubusercontent.com/58944642/101709149-99382b80-3a97-11eb-82e5-bcb93eb261da.png)
(sample 2)
![image](https://user-images.githubusercontent.com/58944642/101709307-e0262100-3a97-11eb-8efd-9cf32926745b.png)

and the result in Waveform View (25000 waveforms):
![image](https://user-images.githubusercontent.com/58944642/101709522-4c088980-3a98-11eb-9fe5-82cc33d0b301.png)

But on the Amplitude view two clear peaks/amplitudes could be seen:
![image](https://user-images.githubusercontent.com/58944642/101709613-778b7400-3a98-11eb-86fd-c682ee353de2.png)

This leads to pooling most of the spikes either real or apparent into one cluster that is, in fact often made of good quality spikes mixed with noise. PCA plots have several partially overlapping clusters (similar to issue https://groups.google.com/g/spyking-circus-users/c/I2b7oqk38zY) 

To search for an explanation I looked at Meta-merging GUI and found that whereas some template pairs look similar (see figure below)
![Screenshot_2020-12-10_18-48-18](https://user-images.githubusercontent.com/58944642/101818938-40b36d80-3b2d-11eb-8e75-1e638255a981.png)

others are clearly not, whereas they are reported as highly similar:
![Screenshot_2020-12-10_18-48-56](https://user-images.githubusercontent.com/58944642/101819003-59238800-3b2d-11eb-9e1d-1f5ca4591363.png) 

Could this be the reason for fitting shown above? Will, in your opinion, increase in number of templates give any improvement? Or could you otherwise give an advise, how could one optimize sorting parameters ?

**Comment by yger** [comment]
I'll have to think a bit about this, but what you are observing is to some extend normal: similarity is computed between normalized templates, i.e. we just compare the shapes, not the amplitudes. The rationale behind that was that, when templates are on numerous channels, if you see twice the same up to an amplitude factor, this is likely to be a burst or a drift. So the code merge them automatically internally. Here, on how many channels are your templates defined? Not much I would say, so the code assumes this is the same, up to an amplitude factor. We should I guess find a better way of preventing such a behavior, I'll try to come up with a solution once for all, because this is something concerning many users with templates on few channels only

**Comment by yger** [comment]
And just because I deleted your data (and the link is not valid anymore...) what is happening if you set templates_normalization = False in the [clustering] section. Does this problem disappears? In theory it should, but maybe at the cost of a slower fitting procedure...

**Comment by SaraMati** [comment]
Hi Pierre, yes, it's a concern. can you point to where in the code this amplitude factor is applied (or explain it here please) because I think the problem can be resolved by having a stricter amplitude factor threshold ...

**Comment by yger** [comment]
Ok, so currently, by default, templates are normalized internally, i.e. we mostly care about the shape of them. This is important for the template matching step, but also for the merging and estimation of amplitudes. As I've said, as long as your templates are on several channels, this is fine, shape is the most important difference. 
In recent version, you do not need to worry about amplitudes, so I think you should not be focused on amplitude factors. The bug for auto estimation being fixed in windows, they are computed automatically to be the best GIVEN this assumption of normalization. 
How do we do that exactly? We solve a partition problem. You have all your templates (normalized) and you ask yourself: how should I set my boundaries optimally in order to get all and only all the spikes for this template, given all the others? This is perfect, if all your templates have different shapes, on many channels. But now imagine your templates are on only a single channel, almost alike, up to an amplitude factor. 
If you have in your dictionary two templates, A and 2A for example, sadly, during this estimation of the amplitudes, the boundaries for A will be computed taken thinking the snippets of 2A are valid (because of the normalization). This is problematic for some situation, and this is why we have the option to turn off this normalization of the templates. By doing so, merging/amplitudes are computed taking into account the shape AND the amplitudes of the templates. But it has a cost: during the template matching step, it can slow down slightly everything because each time you have a spike, if templates are not normalized, you'll always try to test first all the templates that are the largest. It can be time consuming, because you know at the end that you'll throw them away. So I'm looking for feedback on that, since for use, our use case leans more towards templates being normalized by default

**Comment by sv-bio** [comment]
Dear Pierre,
I just finished analysis with templates_normalization = False and merging_param  = 1 (nd-bhatta). I've got 213 templates (likely similarly to issue #266), but in my case is was feature, not bug, because SC managed to tear apart mixtures of spikes I had earlier as huge clusters, so now each small cluster is much cleaner.
I think, the issue can be closed for now.
