### ISSUE TITLE
Can one spike belong to two clusters?

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#330]
Dear Pierre,

One more case report: I have a channel with rather large spikes (300 uV+). They were sorted to two clusters: the first one and one of its peaks:
![Screenshot_2020-12-11_00-00-36](https://user-images.githubusercontent.com/58944642/101835108-f689b680-3b43-11eb-8884-1bdd7230c662.png)

The second one and, to my surprise, the same peak (shift by 0.1 ms; notice also periodic pattern in WaveForm view):
![Screenshot_2020-12-10_21-47-10](https://user-images.githubusercontent.com/58944642/101835228-22a53780-3b44-11eb-97e3-c24f0ce95d5c.png).

I haven't checked the other channels, but this one has substantial number of such "double" counts.

System
Debian 10.6
SC 1.0.6
parameters:
[sorting.txt](https://github.com/spyking-circus/spyking-circus/files/5676065/sorting.txt)

Best,
Stan

**Comment by yger** [comment]
This is with normalization or without? A single spike time on a given channel can not, per se, belong to two clusters. But there could be a one time step difference, and one other one could be fitted. Based on your image, I do not know what to say. I would be tempted to throw away the second cluster, since it looks like this is just a residual of the first large one. The big spikes, when subtracted from the data (because it has been found by the algorithm) can leave some trace in the residuals if they are not perfectly aligned. In theory, this should be taken care by the algorithm, but here, maybe there is still something, found as a simple noise peak, and fitted again

**Comment by sv-bio** [comment]
Dear Pierre,
This was with normalization. I managed to partition the second cluster (figure 2) such that one of its pieces contained an example spike along with other similar spikes (a few dozens of them). Now I have a cohort of clusters that are different by 0.1 ms and each has roughly 40-70 spikes. Maybe, as mentioned in the issue #322, we could think of an algorithm that merges clusters with so little difference.
Sincerely,
Stan
