### ISSUE TITLE
sorting channel independently

### ISSUE THREAD

**Issue by fredchen00** [spyking-circus/spyking-circus#335]
Hi,
Recently, I am working on a dataset collected using multichannel system. I am trying to perform spike sorting on each individual channel independently. To my understanding, I should be able to perform that by setting radius in the prb file and params to 0. I have also set up my electrode to be on proper distance(100um). However, my result for template_ind.npy still come out to be [num of template , 2]. I am not sure why it is still taking neighboring channels as feature. Are there other parameters I should set? 

Thanks in advance,

Fred

**Comment by yger** [comment]
Actually, now with SC, you do not control the final number of channels for the templates. The radius is only used internally during the clustering (and I suggest to let it as it is, to 100um because it can not hurt), and then, SC will automatically estimate the templates on all channels, keeping only the ones with some signal. If at the end you have templates that are not limited to a single channel, then it means that the nearby channels have some residual signal, that can still be useful.. If you really want to have templates on only one channel, then you must define shanks in the .prb file (templates are then restricted internally to shanks)

**Comment by fredchen00** [comment]
Thanks for the quick response. I will try it out
