### ISSUE TITLE
Build and publish is not working

### ISSUE THREAD

**Issue by yger** [spyking-circus/spyking-circus#346]
Not sure this is the fault of the script, but recently, the build_and_publish script is nto working properly, complaining about MPICH installation. Look like the apt-get command is not able to fetch the packages, and I am not sure we have any control on that... Does it alter the behavior if I am tagging a new release?

**Comment by mstimberg** [comment]
Ah, indeed, this can happen if the `apt` database is out of date, it will try to download a package that does not exist anymore because it has been superseded by a newer version. I took the liberty to fix this directly in the master branch (by calling `apt update` first), and it seems to be working fine now. 

Fixed via f5dba8f.
