### ISSUE TITLE
phy gives valueError when trying to run circus-gui-python

### ISSUE THREAD

**Issue by shashwatsridhar** [spyking-circus/spyking-circus#79]
Hey,

I am facing a problem when trying to visualize data using the phy gui. I processed the data and ran the conversion step on a cluster and then transferred all the data onto my pc. When i run the `circus-gui-python path/file.extension` command, this is the result:

```
-------------------------  Informations  -------------------------
| Launching the phy GUI...
------------------------------------------------------------------
19:52:20 [I] messages:49          Launching the phy GUI...
19:52:20 [E] cli:39               An error has occurred (ValueError): shapes (493,61,1) and (96,96) not aligned: 1 (dim 2) != 96 (dim 0)
```
My guess is, 96 corresponds to the number of channels in my dataset, but I don't know what the (493, 61, 1) could correspond to.

I then inserted certain print commands into the python_gui.py file and discovered that the error occurs at line 132, where the TemplateController class is called from phycontrib. Before I go forth debugging phycontrib, I wanted to ask you if there was a way to fix this error in spyking-circus itself. Or, if there was a way to get a more helpful error message.

Thanks!

**Comment by yger** [comment]
I think that this is a problem with phy, and the fact that it is currently
not able to open/display datasets where PCs are located only on a single
chanel. I made a PR to fix the problem, but it is still pending (
https://github.com/kwikteam/phy-contrib/pull/133). Is it your case? Do you
have PCs or spikes that are restricted to 1 channel only?

Best

Pierre

Le dim. 17 juin 2018 à 20:10, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by MusicallyEternal** [comment]
Dear Pierre, I am really sorry for 18 days of inactivity. I was caught up in multiple other things and truly didn't have time to come back to Spyking Circus. 

Yes, that is my case. The spikes/PCs are restricted to a single channel. I am assuming you're referring to how many channels I am expecting the spikes to appear in. Our data comes from a MEA where the electrodes are too far apart to observe the same spike on neighbouring electrodes (utah array, pitch: 400microns). Any update on this front in all these days?

**Comment by MusicallyEternal** [comment]
I installed phy-contrib from your repository, but I run into this error.

```
circus-gui-python i140703-001.dat
Traceback (most recent call last):
  File "/home/sridhar/anaconda2/envs/spycir/bin/circus-gui-python", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'circus-gui-python')()
  File "/home/sridhar/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sridhar/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/sridhar/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/sridhar/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sridhar/Work/Juelich/spyking-circus/spyking-circus/build/lib/circus/scripts/python_gui.py", line 2, in <module>
    import os, shutil, phycontrib
  File "/home/sridhar/anaconda2/envs/spycir/lib/python3.5/site-packages/phycontrib/__init__.py", line 15, in <module>
    from .kwik import *  # noqa
  File "/home/sridhar/anaconda2/envs/spycir/lib/python3.5/site-packages/phycontrib/kwik/__init__.py", line 10, in <module>
    from .gui import KwikGUIPlugin, KwikController  # noqa
  File "/home/sridhar/anaconda2/envs/spycir/lib/python3.5/site-packages/phycontrib/kwik/gui.py", line 18, in <module>
    from phy.cluster.supervisor import Supervisor
ImportError: No module named 'phy.cluster.supervisor'
```

**Comment by yger** [comment]
Ok, I'll have a look and let you know asap. Meanwhile, can you just confirm
that the MATLAB GUI is working, and that you can at least visualize your
results?

Pierre

Le jeu. 5 juil. 2018 à 16:13, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by yger** [comment]
I've tested here, and everything is working :-(

Could it be that you are not using the latest version for phy, installed
from git (you need it to have everything working)? To do so, you must
install phy with the following command

>> pip install git+https://github.com/kwikteam/phy --upgrade

(in case of doubt, please remove everything first with pip uninstall phy,
then reinstall)

**Comment by MusicallyEternal** [comment]
I'll test Matlab soon, in the next few hours maybe, and let you know!

**Comment by yger** [comment]
Ok, we are getting there. Since you have a suffix, you need to convert the
data for phy with the suffix first. Have you launched the following command
before the circus-gui-python

>> spyking-circus i140703-001.dat -m converting -e spycir



Le ven. 6 juil. 2018 à 12:29, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by MusicallyEternal** [comment]
So, I have done that, but without adding the `-e suffix` argument. I ran the following commands as a part of a shell script that runs on our cluster here.

```
spyking-circus /tmp/$workingfile.dat -c 48 -H working.hosts
spyking-circus /tmp/$workingfile.dat -m converting -c 48 -H working.hosts
```

Then i copy all the files down to my PC and run it with the `circus-gui-python` command. I run the commands on the cluster in a conda environment named `spycir`, which is probably why it seems to automatically add th `spycir` suffix to all the files. Anyhow, the results of the `converting` step are saved in the `filename.GUI` folder, correct? I have the folder in the list of files i pasted above.

Should i be running with the -e extension, or can I continue without?

**Comment by yger** [comment]
I'm not sure to follow... After a run of the algorithm, on a data file
named mydata.xxx, you should have files named
mydata/mydata.templates.hdf5 mydata/mydata.basis.hdf5 and so on...

Then, you need to launch the converting step if you want to use the phy
GUI. This will create a folder mydata/mydata.GUI with all the files needed
by phy.

And then, you can launch the circus-gui-python command to visualize
everything with phy. Everything should be rather smooth and is working here.

I don't understand why your files have the suffix spycir in the names,
because this should not happen (except if you used a suffix in the
parameter file, is it the case?)

You should only use the -e extension argument in
converting/circus-gui-python if you used the meta merging GUI. Otherwise,
it should work. So let's try first to understand why your names have the
spycir string inside..


Le ven. 6 juil. 2018 à 14:01, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by alexgonzl** [comment]
So I have had some success running spyking circus, but I keep running into a recurrent issue during the whitening step:
```
numpy/linalg/linalg.py", line 95, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```
Any thoughts on this?

**Comment by MusicallyEternal** [comment]
Okay, first:

I tried running the visualization in matlab but it hasn't worked. I am attaching the output, with additional debugging output that I included in the `h5info.m` file.

```matlab
>> SortingGUI(30000, '/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.dat', '.mat', '/home/s.sridhar/spyking-circus/data/mapping.hdf5', 2)

Filename:
/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.dat.templates.hdf5

Location:
/
Error using h5infoc
Unable to open file. Filename may be corrupt or have unsupported characters.

Error in h5info (line 76)
hinfo = h5infoc(filename,location);

Error in SortingGUI>SortingGUI_OpeningFcn (line 134)
    info     = h5info(tmpfile);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in SortingGUI (line 47)
    gui_mainfcn(gui_State, varargin{:});
```
It seems the script is adding an additional .dat to the filename that it shouldn't.

So, then I inserted a simple function to remove the .dat from the filename and see if the script worked. The modification I made was...

```matlab
    fclose(fid);
end

fprintf('\nFilename:\n%s\n', filename)
filename = erase(filename, string('.dat'))
fprintf('\nNew Filename:\n%s\n', filename)
fprintf('\nLocation:\n%s\n', location)
hinfo = h5infoc(filename,location);

hinfo.Filename = filename;

% If it is a dataset, remove the leading directory paths.
if isfield(hinfo,'ChunkSize')
```

but it still yields this output...

```matlab
>> SortingGUI(30000, '/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.dat', '.mat', '/home/s.sridhar/spyking-circus/data/mapping.hdf5', 2)

Filename:
/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.dat.templates.hdf5

filename =

/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.templates.hdf5


New Filename:
/home/s.sridhar/spyking-circus/data/results/i140703-001/i140703-001.templates.hdf5

Location:
/
Error using h5infoc
Unable to open file. Filename may be corrupt or have unsupported characters.

Error in h5info (line 78)
hinfo = h5infoc(filename,location);

Error in SortingGUI>SortingGUI_OpeningFcn (line 134)
    info     = h5info(tmpfile);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in SortingGUI (line 47)
    gui_mainfcn(gui_State, varargin{:});
```

**Comment by MusicallyEternal** [comment]
Second:

I realised what mistake I was making with the python gui, and i think it's something you need to mention on your documentation online.

I was processing all the data on a cluster, where it would be stored and run from the `/tmp/` folder. To visualize the results, I copy the resulting files onto my computer and put them in a different directory structure altogether (`/home/...`). To avoid the error i was getting earlier, I need to change the corresponding entries in the `.params` file where I had specified `mapping` and `output_dir` so that they now point to the updated locations of the mapping and data files. This is not clear in the documentation online.

You were right, though, I had unnecessarily meddled with `suffix` parameter as well, and i changed that. Thanks!

Having changed that, even though I don't get the `templates file not found` error, I still can't get the GUI to run. This time, it doesn't output anything. Nothing shows up on the screen, no information messages on the terminal. Strange, I'd say. Any idea how I could debug this?

**Comment by yger** [comment]
Dear Shashwat

I'm a bit puzzled with all your errors, I finally don't really understand
what is solved or not. For the python GUI, if this is not displaying
anything, this is probably because phy is not well installed. Please be
sure to do

>> pip install vispy traitlets click joblib
>> pip install git+https://github.com/kwikteam/phy git+
https://github.com/kwikteam/phy-contrib --upgrade

For the MATLAB GUi, I'm not sure to understand. You are telling me that the
command circus-gui-python is crashing? If yes, what is the matlab version,
hdf5 version, spyking-circus version?

**Comment by MusicallyEternal** [comment]
Alright, I'll try and explain my errors more systematically.

### Python GUI errors:

I am running spyking-circus on a cluster at my institute and then trying to visualise the corresponding results on my laptop. I have installed all the required python packages (including spyking-circus, phy and phycontrib), in conda environments on both, the cluster and my laptop. On the cluster, I use the following commands to spike sort my data:

```
spyking-circus /tmp/$workingfile/$workingfile.dat -c 48 -H working.hosts
spyking-circus /tmp/$workingfile/$workingfile.dat -m converting -c 48 -H working.hosts
```

Earlier I had the error that all processed files were generated with a strange suffix. But, you diagnosed that problem correctly. I had modified the `suffix` parameter in the parameter file, which is why there were suffixes. 

After fixing the above error, I copied all the files from the cluster to my computer so I could visualize them. I ran the `circus-gui-python datafile.dat` command (in the correct folder) and it just showed me:

```
/home/s.sridhar/spyking-circus/data/results/i140703-001$ circus-gui-python i140703-001.dat 
-------------------------  Informations  -------------------------
| Launching the phy GUI...
------------------------------------------------------------------
```
and then nothing further happened. No GUI window opened. I reinstalled Phy and Phycontrib. I also created a fresh conda environment and installed all the packages there, but even that didn't help. It doesn't show any further error messages, so i inserted some print commands into the `circus/scripts/python_gui.py` file to debug. The last line that was successfully executed was `create_app` on line 131. There is probably an error in creating the `controller` on the next line (line 132), and I am guessing this is a phy_contrib error. I then tried installing your branch of phy_contrib, but that doesn't solve the issue.

### Matlab GUI error:

I have managed to get the data to load in the matlab-gui after making some small changes to the matlab_gui.py script. I don't think the changes were bugs in the code, so I will not pursue this further. What this does mean, though, is that my data has been correctly sorted and I'd like to run it using the Phy GUI. 

### Further question:

I am trying get the python-gui to work because I want to have a quick and easy way to visualize the results of spike sorting. But eventually, I want to be able to use this data for further analysis, for which I would need the templates, waveforms and timestamps arranged electrode-wise in a single file. We have manually sorted data that we store in blackrock .nev files, so in principle I'd like the data converted to that, or a similar format. 

My question is, do you have any simple python scripts (independent of Phy) I could use that load the different files generated by spyking-circus, so I can save the required parts of the data in my desired format? Also, I noticed that the waveforms (or 'snippets') corresponding to each spike time are not stored at the end of the spike sorting. Is this correct? Is there a way to save those as well in spyking-circus?

**Comment by yger** [comment]
If you have a look here 
http://spyking-circus.readthedocs.io/en/latest/advanced/gui.html
 
You should be able to create a params.py file such that you can launch the phy GUI differently
>> phy template-gui params.py

In fact, I think this params.py file may even be created automatically when you launch the circus-gui-python command, so check in the mydata/mydata.GUI folder if present. The good point, with such a way of launching the phy GUI, is that you can do
>> phy template-gui params.py --debug

You'll then see why the GUI is not working, and have a better feedback on error messages

Regarding the data of SpyKING CIRCUS, they are described here http://spyking-circus.readthedocs.io/en/latest/advanced/files.html. What do you mean by "script to load the data"? This depends on what you want to visualize... Just templates, spikes and waveforms? Example scripts can be found here http://spyking-circus.readthedocs.io/en/latest/advanced/analysis.html 
However, as you noticed, individual waveforms are not saved in these files, simply because this can not scale for large recordings. If you want, I can provide you python scripts to extract snippets of the data at the times where the algorithm founds spikes. But no mystery there, they will look exactly like the template, because this is how the algorithm is constructed
