### ISSUE TITLE
Cannot run multi-file stream on OpenEphys?

### ISSUE THREAD

**Issue by warnerwarner** [spyking-circus/spyking-circus#88]
Whenever I try to run on Openephys I get the following error:
 ----------------------------  Error  -----------------------------
| The file format openephys does not support stream mode multi-file
------------------------------------------------------------------
But in the documentation it says it should be supported? If I change it to None I can run it on a single instance, but am unable to run it over multiple CPUs.

**Comment by yger** [comment]
In fact, the multi-file mode is not working for openephys, sorry for the
mistake in the documentation. This is because the openephys file format
already involved several files (one per channel), so I must make minor
changes to support it, as I just did for the neuralynx file format, that
has the silame problem. I could plan to do so if you are interested by the
feature, but it will take few days at least. What is your typical workflow?
You have several recordings (each of them composed of several files),
organised in different folders?

Le ven. 28 sept. 2018 à 17:18, Tom Warner <notifications@github.com> a
écrit :

**Comment by warnerwarner** [comment]
Yes, you're correct, I have several recordings, composed of several file, with each file referring to one channel, and I'm trying to run spyking circus over a cluster. It'd be interested if it could run straight from OpenEphys, but I can also convert it myself to raw_binary or numpy.

**Comment by yger** [comment]
I'll try to make the multi-file mode compatible with openephys, but as said
it will take few days. Meanwhile, as you are saying, you can convert to
several raw binary files, and use the multi-file mode. But I agree this
would be more clean keeping your original files.

Le ven. 28 sept. 2018 à 17:58, Tom Warner <notifications@github.com> a
écrit :

**Comment by yger** [comment]
I created a "multi-folders" mode for OpenEphys, as multi-files is complicated since they all have the same names. Basically, if you launch the code on folder0/data.openephys, the multi-folders mode will search for all data files in folderXX/data.openephys, and process them as a single file
